### ISSUE TITLE
Wanna join the group buy.

### ISSUE THREAD

**Issue by quangbuule** [oblotzky/sa-oblivion#2]
Hello,

I know this is not appropriated place for asking things like this, so I am sorry for any inconvenience.
I didn't know there was a GB for the keyset that I am desiring so bad (although I haven't got any keyset before). Is there any chance that I could be in the GB? (I use Minila Layout).

My email is quangbuule@gmail.com
Feel free to close this issue.

Thanks so much,
Quang-Buu Le

**Comment by oblotzky** [comment]
Hello,

it is not an inconvenience at all! Thank you for your interest in this set, but unfortunately the sale for it has been closed on Massdrop.com for a few months now. There are no additional units that I can offer you, your best chance for getting these are the following:

Firstly, once the set has shipped out in roughly Q2 2018, some people will look to resell it for profit on places such as reddit.com/r/mechmarket.

Secondly, Massdrop usually buys extra units to cover losses or other support requests. Once those are no longer needed, they are sold as retail units in keycap sales like the recent 'Keycap Re-Cap' (https://www.massdrop.com/buy/capatoa-keycap-explosion).

I hope this helps! Good luck.

- Oblotzky
